name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: samsmithnz/ReusableWorkflowsDemo/.github/workflows/build.yml@v1
    with:
      project: "My magic project"

  test:
    uses: samsmithnz/ReusableWorkflowsDemo/.github/workflows/test.yml@v1
    with:
      project: "My magic project"

  deployToDev:
    needs: 
    - build
    - test
    uses: samsmithnz/ReusableWorkflowsDemo/.github/workflows/deploy.yml@v1
    with:
      projectPackage: "MyMagicProject.zip"
      environment: dev
      scale: '1'
      cloud: Azure
      
  deployToQA:
    needs: 
    - deployToDev
    uses: samsmithnz/ReusableWorkflowsDemo/.github/workflows/deploy.yml@v1
    with:
      projectPackage: "MyMagicProject.zip"
      environment: qa
      scale: '2'
      cloud: Azure

  deployToProd:
    needs: 
    - deployToQA
    uses: samsmithnz/ReusableWorkflowsDemo/.github/workflows/deploy.yml@v1
    with:
      projectPackage: "MyMagicProject.zip"
      environment: prod
      scale: '5'
      cloud: Azure
